version: '3.8'

services:
  streaming-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9093,kafka-3:9094
      - LOG_LEVEL="info"
    ports:
      - "8081:8081"